---
title: "01-comandos.Rmd"
author: "eveiramirez"
date: "4/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Proyecto  
A continuacion se presentara el estudio SRA SRP102549, el cual es un analisis de
transcriptoma con datos de 81 lineas celulares de cancer de higado.  

Identificadores  
SRA:[SRP102549](https://trace.ncbi.nlm.nih.gov/Traces/sra?study=SRP102549)  
BioProject:[PRJNA380668](https://www.ncbi.nlm.nih.gov//bioproject/PRJNA380668)  
GEO:[GSE97098](https://www.ncbi.nlm.nih.gov//geo/query/acc.cgi?acc=GSE97098)  

PubMed Link  
PUBMED:[31378681](https://www.ncbi.nlm.nih.gov//pubmed/31378681)


```{r start, warning=FALSE, message=FALSE, eval=FALSE}
## Cargar el paquete recount3 y iSEE
library("recount3")
library("iSEE")

```


```{r project, eval=FALSE}
### Se obtienen los datos del proyecto  
rse_project_srp102549 <- recount3::create_rse_manual(
    project = "SRP102549",
    project_home = "data_sources/sra",
    organism = "human",
    annotation = "gencode_v29",
    type = "gene"
)

```


```{r tranform counts, eval=FALSE}
assay(rse_project_srp102549, "counts") <- transform_counts(rse_project_srp102549)

```


```{r expand attributes, eval=FALSE}
## Expandir los atributos sra
rse_project_srp102549 <- expand_sra_attributes(rse_project_srp102549)

```


colData(rse_project_srp102549)[
    ,
    grepl("^sra_attribute", colnames(colData(rse_project_srp102549)))
]

iSEE::iSEE(rse_project_srp102549)

```{r quality control, eval=FALSE}
## Obtener proporcion de lecturas asignadas
rse_project_srp102549_qc<-rse_project_srp102549
rse_project_srp102549_qc$assigned_gene_prop <- rse_project_srp102549$recount_qc.gene_fc_count_all.assigned / rse_project_srp102549$recount_qc.gene_fc_count_all.total


summary(rse_project_srp102549_qc$assigned_gene_prop)
hist(rse_project_srp102549_qc$assigned_gene_prop)
rse_project_srp102549_qc <- rse_project_srp102549_qc[, rse_project_srp102549_qc$assigned_gene_prop > 0.75]

gene_means <- rowMeans(assay(rse_project_srp102549_qc, "counts"))
summary(gene_means)
plot(gene_means)
rse_project_srp102549_qc <- rse_project_srp102549_qc[gene_means > 0.1, ]

```





## Referencias
```{r citation, message = FALSE, echo=FALSE}
## Citation info
print(citation("recount3")[2], bibtex = TRUE) 

```
